import StyledComponentsRegistry from '../lib/registery'
import { Providers } from './globalRedux/provider'
import { Navbar } from './components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import { Footer } from './shared/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hotel Bambu',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <StyledComponentsRegistry>
            <Navbar />
            {children}
            <Footer />
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  )
}
